### PR TITLE
highlightWeekDays prop 

### PR DESCRIPTION
**Pull request by devhus**
feat: added highlightWeekDays prop to highlight all dates under a weekday

### CODE REVIEW

**Comment by Jasenkoo** [comment]
@devhus Looking fine, however, can you run `npm run lint` and create pull again?

**Comment by devhus** [comment]
> @devhus Looking fine, however, can you run `npm run lint` and create pull again?

done.

**Comment by devhus** [comment]
@Jasenkoo Do i need to create another PR or recreate my fork?

**Comment by Jasenkoo** [comment]
@devhus No need, I will merge it today.

**Pull request merged**
