### PR TITLE
feat(global): Adding configuration to support app using @vue/compat

### PR DESCRIPTION
**Pull request by fanta759**
I didn't get app compatible with Vue 2.
But for app in Vue 3 with @vue/compat dependancy some configuration is needed.
I add this configuration for all component and now the datepicker is working nicely.

### CODE REVIEW

**Comment by Jasenkoo** [comment]
I don't quite follow, Do you already have a Vue 3 app?

**Comment by fanta759** [comment]
Here is a sample to see what i mean: https://stackblitz.com/edit/vitejs-vite-yhjjur?file=src%2Fcomponents%2FHelloWorld.vue

I have to use @vue/compat because I'm using the Bootstrap-Vue library, which hasn't yet been converted to Vue3.
However, it is compatible with a Vue3 application with @vue/compat: https://bootstrap-vue.org/vue3

**Comment by edufalcao** [comment]
Hello @Jasenkoo!

First, thanks for this lib! :) Just want to ask if you have a planned date to release the change from this PR. I am testing your lib with Vue3 running with `vue-compat` and I am facing similar issues.

**Comment by yanislav-igonin** [comment]
same question here
tnx in advance!

**Pull request merged**
